function motion = makeHeader(outfile, dataRate, ...
    instructions)
latestTime = getLatestTime(instructions);
motion = [ ...
    outfile, newline, ...
    'version=1', newline, ...
    'nRows=', num2str(latestTime*dataRate), newline, ...
    'nColumns=', num2str(getNumColumns(instructions)+1), newline, ...
    'inDegrees=yes', newline, ...
    'endheader', newline ...
    ];
end

function numCols = getNumColumns(instructions)
uniqueCoords = getUniqueCoords(instructions);
numCols = length(uniqueCoords);
end